version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
