import { Renderer } from "./renderer/definition";
import {
  DeferredLightingConfiguration,
  DeferredLightingHandle,
  DeferredLightingLightModel,
  DeferredLightingRenderer,
  DeferredLightingScene,
  DeferredLightingSubject,
  createDeferredLightingRenderer,
} from "./renderer/deferred-lighting";
import {
  DeferredShadingConfiguration,
  DeferredShadingHandle,
  DeferredShadingLightModel,
  DeferredShadingRenderer,
  DeferredShadingScene,
  DeferredShadingSubject,
  createDeferredShadingRenderer,
} from "./renderer/deferred-shading";
import {
  createForwardLightingRenderer,
  ForwardLightingConfiguration,
  ForwardLightingHandle,
  ForwardLightingLightModel,
  ForwardLightingRenderer,
  ForwardLightingScene,
  ForwardLightingSubject,
} from "./renderer/forward-lighting";
import {
  SoftwareDrawMode,
  SoftwareRenderer,
  SoftwareScene,
  SoftwareSubject,
  createSoftwareRenderer,
} from "./renderer/software";

export {
  type DeferredLightingConfiguration,
  type DeferredLightingHandle,
  type DeferredLightingRenderer,
  type DeferredLightingScene,
  type DeferredLightingSubject,
  type DeferredShadingConfiguration,
  type DeferredShadingHandle,
  type DeferredShadingRenderer,
  type DeferredShadingScene,
  type DeferredShadingSubject,
  type ForwardLightingConfiguration,
  type ForwardLightingHandle,
  type ForwardLightingRenderer,
  type ForwardLightingScene,
  type ForwardLightingSubject,
  type Renderer,
  type SoftwareRenderer,
  type SoftwareScene,
  type SoftwareSubject,
  DeferredLightingLightModel,
  DeferredShadingLightModel,
  ForwardLightingLightModel,
  SoftwareDrawMode,
  createDeferredLightingRenderer,
  createDeferredShadingRenderer,
  createForwardLightingRenderer,
  createSoftwareRenderer,
};
