name: Validate

on:
  - push

jobs:
  check:
    name: Check types
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm run check
