name: Verify

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "10 4 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm install
      - run: npm run check
      - run: npm run test

  validate:
    name: Validate
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - run: true
