name: Verify

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "10 4 * * *"

jobs:
  install:
    name: Install revision
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - uses: actions/upload-artifact@v4
        with:
          name: install
          path: .

  check:
    name: Check style
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/download-artifact@v4
        with:
          name: install
          path: .
      - run: npm install
      - run: npm run check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/download-artifact@v4
        with:
          name: install
          path: .
      - run: npm install
      - run: npm run test
